name: markdown-link-check

on:
  push:

jobs:
  markdown-link-check:
    name: Check markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Markdown links check
        uses: ruzickap/action-my-markdown-link-checker@v1
        with:
          exclude: |
            Adding-new-translations-for-i18n.md
            Apache-Beam-Jobs.md
            Coding-style-guide.md
            Contributing-code-to-Oppia.md
            Developing-new-features-with-feature-gating.md
            End-to-End-Tests.md
            Find-the-right-code-to-change.md
            Backend-Type-Annotations.md
            Frontend-tests.md
            Backend-tests.md
            GHC-Open-Source-Day-2019.md
